export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PASS_IMGAGE_CHANGE = 'PASS_IMGAGE_CHANGE';
export const PASS_INPUTS_CHANGE = 'PASS_INPUTS_CHANGE';
export const PASS_TYPE_CHANGE = 'PASS_TYPE_CHANGE';
export const PASS_RESET = 'PASS_RESET';
export const PASS_SET_UPLOADED_IMG = 'PASS_SET_UPLOADED_IMG';
